#ifndef __PULSE_CACTUAR_ENCODING_H__
#define __PULSE_CACTUAR_ENCODING_H__

#include <stddef.h>

/*----------------------------------------------------------
* Note: We're assuming that the endianess of floats, 
*       which we're also assuming is IEEE-754, 
*       has the same endianess as integers on the platform.
------------------------------------------------------------*/



/*************************************************************
* Encodes a data as little endian.
* 
* If the system is already little endian then **data** is just 
* copied into **encoded** with a pointer cast.
* 
* encoded's value is decoupled from **data** and therefore will not 
* have any unintended side effects 
* 
* @param[in]  data  is a ptr to a data to be encoded
* @param[out] encoded must have at least size bytes and will point to data in
* little endian order.
* @param[in]  size    is the size of the data of bytes "data" has
***************************************************************/
void encode_data(const void *const data, unsigned char *encoded, size_t size);

/******************************************************************************
* Converts a data as little endian (overwriting data)
* 
* If the system is already little endian then **data** is just cast to 
* and unsigned char. This is faster than **encode_data** but in the case
* the system is not little endian, data will have the wrong format and will
* not contain the same value passed in.
* 
* The returned pointer's lifetime is dependant upon data as it points to the same location.
* 
*
* The returned pointer points to **data** and therefore there may be unintended side effects
* when modifying its value. However this can also be of use, we use this to mdoify a 
* floating point data's binary representation in math.c
* 
* The returned pointer can also be passed into **decode_data** but again this will modify
* **data**
* 
* @param[in] data is a ptr to a data to be converted
* @param[in] size   is the size of the data of bytes **data** has.
* @return The returned pointer will live only as long as **data**
*         does (since it just points to it).
******************************************/
unsigned char* convert_data(void* data, size_t size);


/*************************************************************
* Decodes a data from little endian.
*
* If the system is already little endian then encoded returned
* unchanged. 
* Otherwise the data is converted to back into big endian. Note that is
* encoded was generated by **convert_data** then the **data** argument
* passed in will also be modified by this function as long as encoded
* still points to data (as would be the case in **convert_data**.
* 
* decode_data does almost exactly the same thing as convert data,
* its primarily for increased code readability, avoids one useless cast and
* is somewhat more type tidy.
*
* @param[in,out] encoded must have at least size bytes and its bytes will be
* translated back into the systems endianness.
* @param[in] size is the size of the data of bytes "data" has
***************************************************************/
void decode_data(unsigned char* encoded, size_t size);


#endif